### ISSUE TITLE
How would you provide a no-argument called to manufacture default values

### ISSUE THREAD

**Issue by metaperl** [biqqles/dataclassy#1]
In the docs, it stats that a copy is made of data items provided as defaults. But in core dataclasses, you can also supply a `default_factory`. How would you do this in dataclassy?

**Comment by biqqles** [comment]
Thanks for the question. As you pointed out, mutable defaults are copied, so for example `list_field = field(default_factory=list)` in dataclasses becomes simply `list_field: List = []` with dataclassy. Or, as a more complicated example, `dd_field: Dict = field(default_factory=lambda: defaultdict(list))` becomes `dd_field: Dict = defaultdict(list)`.

I couldn't think of a use case this alternative mechanism wouldn't cover. Do you have one in mind?

**Comment by metaperl** [comment]
> I couldn't think of a use case this alternative mechanism wouldn't cover. Do you have one in mind?

What if I have a field that will contain instances of `MyCustomClass`? 

How would I specify this?

**Comment by biqqles** [comment]
If you define a `copy` method for the class it should work.

**Comment by biqqles** [comment]
I suppose this naturally raises the question of whether this is ideal. My thinking, as implied earlier, is that in the clear majority of cases where a default value can't be shared between instances it is for the reason that it is mutable, so copying it will suffice. In the case of collections, this is a clear advantage (imo) since it reduces the repetitiveness of lambdas. This would definitely be a disadvantage if you commonly wanted to create class instances, particularly if you wanted to create instances of classes you don't control.

Another option to the above solution would be to use post-initialisation logic:

```Python
@dataclass
class Example:
    mcc: MyCustomClass = None

    def __init__(self, mcc=None):
        self.mcc = MyCustomClass()
```

This has the major advantage of flexibility - you can do logic as complex as you like in there, including initialising `MyCustomClass` based on other fields of the dataclass or additional parameters to `__init__`. And of course, there is no need to define a `copy` method.

I admit that this is still not as "nice" as dataclasses' `default_factory`. However, adding a `field` clone would go almost violently against dataclassy's ethos of radical simplicity in its own codebase, especially as this is essentially the only parameter that there won't be a lighter-weight equivalent for. That's the reason it's not there already. I'm still very interested in hearing people's thoughts on this though.

**Comment by biqqles** [comment]
As of 03cebc9 this is now possible with

```Python
@dataclass
 class Example:
     mcc: MyCustomClass = None
 
     def __init__(self):
         self.mcc = MyCustomClass()
```
and an example has been added to the README to document this.

**Comment by biqqles** [comment]
For future readers, as of release v0.9, this is now possible:

```python
@dataclass
class Example:
    mcc: MyCustomClass = factory(MyCustomClass)
```
