### ISSUE TITLE
Add __post_init__ for additional compatibility?

### ISSUE THREAD

**Issue by TylerYep** [biqqles/dataclassy#2]
I have existing code that uses dataclasses with `__post_init__`. It would be great if dataclassy would allow me to continue using this function without having to refactor all of my old dataclasses.

`__post_init__` has the added benefit of allowing me to skip redefining the parameter names a second time, e.g.

## Using built-in dataclasses
```
@dataclass
class SolverState:
    possible: Tuple[FrozenSet[str], ...] = ()
    switches: Tuple[str, ...] = ()
    path: Tuple[bool, ...] = ()
    roles: Dict[str, int] = field(default_factory=dict)
    count_true: int = -1

    def __post_init__(self) -> None:
        if not self.possible:
            self.possible = (5,)
        if self.count_true == -1:
            self.count_true = self.path.count(True)
        if not self.roles:
            self.roles = self._roles_init()
```

## Using dataclassy
```
@dataclass(slots=True)
class SolverState:
    possible: Tuple[FrozenSet[str], ...] = ()
    switches: Tuple[str, ...] = ()
    path: Tuple[bool, ...] = ()
    roles: Dict[str, int] = {}
    count_true: int = -1

    def __init__(
        self,
        possible: Tuple[FrozenSet[str], ...] = (),
        switches: Tuple[str, ...] = (),
        path: Tuple[bool, ...] = (),
        roles: Dict[str, int] = {},
        count_true: int = -1,
    ) -> None:
        if not self.possible:
            self.possible = (5,)
        if self.count_true == -1:
            self.count_true = self.path.count(True)
        if not self.roles:
            self.roles = self._roles_init()
```

**Comment by biqqles** [comment]
Hi, sorry for the delayed response. Personally, I'm not a fan of `__post_init__`. In my view, it needlessly corrupts the data model with redundancy: for every other object `__new__` creates an instance of the type and `__init__` modifies that instance. As a result it looks inelegant and unnatural.

**However, the current form of post-initialisation logic in dataclassy is certainly also far from ideal.** All arguments being passed to `__init__` is really very ugly. It would be much more sensible (and attractive) to simply call `__init__` in `__new__` with its own signature, and leave out the completely redundant already-used arguments. I haven't done so yet for a few reasons, including that I need to think about fringe cases (for example, what if you wanted to access `**kwargs` in `__init__`?).

Lastly, remember that you can consume unwanted arguments, so your refactor should be possible right now by find-replacing `__post_init__():` with `__init__(*a, **k):` or similar.

**Comment by biqqles** [comment]
Hi, sorry for the delayed response. Personally, I'm not a fan of `__post_init__`. In my view, it needlessly corrupts the data model with redundancy: for every other object `__new__` creates an instance of the type and `__init__` modifies that instance. As a result it looks inelegant and unnatural.

**However, the current form of post-initialisation logic in dataclassy is certainly also far from ideal.** All arguments being passed to `__init__` is really very ugly. It would be much more sensible (and attractive) to simply call `__init__` in `__new__` with its own signature, and leave out the completely redundant already-used arguments. I haven't done so yet for a few reasons, including that I need to think about fringe cases (for example, what if you wanted to access `**kwargs` in `__init__`?).

Lastly, remember that you can consume unwanted arguments, so your refactor should be possible right now by find-replacing `__post_init__(self):` with `__init__(self, *a, **k):` or similar.

**Comment by TylerYep** [comment]
I agree, but I do think the README is a bit misleading then, since it suggests that migrating to dataclassy is as simple as changing the import line -- those exceptions should probably be documented.

I was hoping for a simple solution (e.g. simply defining a `__post_init__()` function that just calls dataclassy's `__init__()`, in order to avoid having to do any refactoring of existing dataclasses) -- but I understand if that was not the primary goal of this project, or if it is not as simple as I am envisioning.

I agree that __post_init__ is ugly, but compatibility is important in order to simplify migration to this project, which I think has a lot of great potential 👍

**Comment by biqqles** [comment]
Agreed - that section ought to be rewritten and the differences made explicit. I intended the [Examples](https://github.com/biqqles/dataclassy#examples) section after [Migration](https://github.com/biqqles/dataclassy#migration) to indicate the pertinent differences but that's far from clear. I will think about how to best clarify this.

Regarding compatibility: I don't think there's good justification for supporting `__post_init__` since it's a simple find-replace "refactor" (especially if the need to consume arguments is removed). The functions `as_dict` and `as_tuple` are aliased but that's simply because doing so is trivial. Handling `__post_init__` would complicate initialiser generation for not much benefit, in my opinion. We could raise a `TypeError` if it is defined though, as the current behaviour of the method never being called and the user left to work out why isn't great.

**Comment by biqqles** [comment]
Agreed - that section ought to be rewritten and the differences made explicit. I intended the [Examples](https://github.com/biqqles/dataclassy#examples) section after [Migration](https://github.com/biqqles/dataclassy#migration) to indicate the pertinent differences but that's far from clear. I will think about how to best clarify this.

Regarding compatibility: I don't think there's good justification for supporting `__post_init__` since it's a simple find-replace "refactor" (especially if the need to consume arguments is removed). The functions `as_dict` and `as_tuple` are aliased but that's simply because doing so is trivial. Handling `__post_init__` would complicate initialiser generation for not much benefit, in my opinion. We could raise a `TypeError` if it is defined though, as the current behaviour of the method never being called and the user left to work out why isn't great.

**Comment by biqqles** [comment]
I've been successful in implementing "clean" initialisation, which is to say that arguments used by `__new__` are not passed through to `__init__`. Even better, this happens completely transparently in that if an argument is not supplied Python will raise a `TypeError` detailing which method expected it (either dataclassy's generated `__new__`, or your own `__init__`). The implementation is in the branch [clean-init](https://github.com/biqqles/dataclassy/tree/clean-init).

Using this branch, your code with dataclassy becomes
```Python
@dataclass
class SolverState:
    possible: Tuple[FrozenSet[str], ...] = ()
    switches: Tuple[str, ...] = ()
    path: Tuple[bool, ...] = ()
    roles: Dict[str, int] = {}
    count_true: int = -1

    def __init__(self):
        if not self.possible:
            self.possible = (5,)
        if self.count_true == -1:
            self.count_true = self.path.count(True)
        if not self.roles:
            pass  # method not included
```
which runs as expected. `__init__` can of course still define its own parameters, including ones with default values. This provides the equivalent of dataclasses' `InitVar`.

Now for the bad news. It seems that merely reimplementing `__call__` in the metaclass (which is required to do the above) breaks `inspect.signature`, causing it to return `(*args, **kwargs)` for the data class. I'll try to work out why this is and if it can be mitigated. As mentioned in the readme, I think this function is important because it allows the exact signature of a generated class to be verified by the user. It's also used in some of dataclassy's own tests.

Overall I'm still extremely encouraged to see that this is possible. It's what I hoped dataclassy's form of post-initialisation logic would look like.

**Comment by biqqles** [comment]
Just an update on progress: despite it seeming to be a simple task to modify the signature of `__new__` slightly to generate a signature for the class, the [`Signature` object](https://docs.python.org/3/library/inspect.html#inspect.Signature) appears to be temperamental to say the least. Calling `replace` even with _unchanged_ parameters results in the dreaded `(*args, **kwargs)`. So this is, unfortunately, slowing things down.

**Comment by biqqles** [comment]
Just an update on progress: despite it seeming to be a simple task to modify the signature of `__new__` slightly to generate a signature for the class, the [`Signature` object](https://docs.python.org/3/library/inspect.html#inspect.Signature.replace) appears to be temperamental to say the least. Calling `replace` even with unchanged parameters results in the dreaded `(*args, **kwargs)`. So this is, unfortunately, slowing things down.

**Comment by biqqles** [comment]
I've merged all the changes described in this issue. If there's something you still think could be clearer, feel free to reopen it.

**Comment by biqqles** [comment]
`__post_init__` is now supported as of release `v0.7`.
