### ISSUE TITLE
__post_init__ and repeated decorator produces max recursion depth

### ISSUE THREAD

**Issue by dand-oss** [biqqles/dataclassy#43]
```
from dataclassy import dataclass


@dataclass
class Base:
    a: int = 0


@dataclass
class Inherit(Base):
    b: int = 0

    def __post_init__(self) -> None:
        pass


inst = Inherit()
```
----
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    inst = Inherit()
  File "<string>", line 4, in __init__
  File "<string>", line 4, in __init__
  File "<string>", line 4, in __init__
  [Previous line repeated 995 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by biqqles** [comment]
The cause is the renaming of `__init__` to `__post_init__` [here](https://github.com/biqqles/dataclassy/blob/master/dataclassy/dataclass.py#L120-L121). Both functions are supported for [post-initialisation processing](https://github.com/biqqles/dataclassy#post-initialisation-processing) but the former is a historical artifact at this point. I've been thinking of removing it as no one seems to use it and it's confusing, this bug makes me think I should. Removing the two lines linked resolves it.

**Comment by biqqles** [comment]
Fixed - will postpone removing `__init__` aliasing to a later issue.
